/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\blog\\blog-new\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-a60d03a6",
    path: "/Photography/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a60d03a6").then(next)
    },
  },
  {
    path: "/Photography/index.html",
    redirect: "/Photography/"
  },
  {
    name: "v-13ebaf95",
    path: "/Photography/back/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13ebaf95").then(next)
    },
  },
  {
    name: "v-552baa45",
    path: "/Photography/front/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-552baa45").then(next)
    },
  },
  {
    name: "v-241e5a9c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-241e5a9c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-ff9f3136",
    path: "/Photography/front/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ff9f3136").then(next)
    },
  },
  {
    name: "v-129c8c25",
    path: "/browser/Console/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-129c8c25").then(next)
    },
  },
  {
    name: "v-4da27585",
    path: "/browser/Console/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4da27585").then(next)
    },
  },
  {
    name: "v-06718f93",
    path: "/Photography/back/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06718f93").then(next)
    },
  },
  {
    name: "v-67308f29",
    path: "/browser/Http/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67308f29").then(next)
    },
  },
  {
    name: "v-64e6f6a7",
    path: "/browser/Http/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64e6f6a7").then(next)
    },
  },
  {
    name: "v-38b61c25",
    path: "/browser/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38b61c25").then(next)
    },
  },
  {
    name: "v-63bad945",
    path: "/browser/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63bad945").then(next)
    },
  },
  {
    name: "v-4e9fac52",
    path: "/browser/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e9fac52").then(next)
    },
  },
  {
    path: "/browser/index.html",
    redirect: "/browser/"
  },
  {
    name: "v-5ae7d52e",
    path: "/browser/SourceCode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ae7d52e").then(next)
    },
  },
  {
    name: "v-edb78194",
    path: "/css/Css/1%20copy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-edb78194").then(next)
    },
  },
  {
    path: "/css/Css/1 copy.html",
    redirect: "/css/Css/1%20copy.html"
  },
  {
    path: "/css/Css/1 copy.html",
    redirect: "/css/Css/1%20copy.html"
  },
  {
    name: "v-ab26c3f6",
    path: "/css/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ab26c3f6").then(next)
    },
  },
  {
    name: "v-3051c3a5",
    path: "/css/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3051c3a5").then(next)
    },
  },
  {
    name: "v-5c3372a5",
    path: "/css/Css/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c3372a5").then(next)
    },
  },
  {
    name: "v-62302021",
    path: "/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62302021").then(next)
    },
  },
  {
    path: "/css/index.html",
    redirect: "/css/"
  },
  {
    name: "v-a25fb702",
    path: "/html/Html/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a25fb702").then(next)
    },
  },
  {
    name: "v-85c41ac2",
    path: "/html/Html/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-85c41ac2").then(next)
    },
  },
  {
    name: "v-481935a1",
    path: "/html/Interview/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-481935a1").then(next)
    },
  },
  {
    name: "v-4a7ab9df",
    path: "/html/Interview/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a7ab9df").then(next)
    },
  },
  {
    name: "v-e3487c42",
    path: "/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e3487c42").then(next)
    },
  },
  {
    path: "/html/index.html",
    redirect: "/html/"
  },
  {
    name: "v-deeca1ce",
    path: "/js/ES6/ES61.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-deeca1ce").then(next)
    },
  },
  {
    name: "v-c251058e",
    path: "/js/ES6/ES62.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c251058e").then(next)
    },
  },
  {
    name: "v-e6578f76",
    path: "/css/Css/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6578f76").then(next)
    },
  },
  {
    name: "v-0eeb1302",
    path: "/js/Function/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0eeb1302").then(next)
    },
  },
  {
    name: "v-33905fdf",
    path: "/js/Function/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33905fdf").then(next)
    },
  },
  {
    name: "v-c55abd82",
    path: "/js/JS/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c55abd82").then(next)
    },
  },
  {
    name: "v-42100e7f",
    path: "/js/JS/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42100e7f").then(next)
    },
  },
  {
    name: "v-467714df",
    path: "/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-467714df").then(next)
    },
  },
  {
    path: "/js/index.html",
    redirect: "/js/"
  },
  {
    name: "v-209d5042",
    path: "/js/JS/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-209d5042").then(next)
    },
  },
  {
    name: "v-22576fec",
    path: "/js/arry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22576fec").then(next)
    },
  },
  {
    name: "v-e7cce0c0",
    path: "/js/ast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e7cce0c0").then(next)
    },
  },
  {
    name: "v-c8ee1702",
    path: "/js/reg/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c8ee1702").then(next)
    },
  },
  {
    name: "v-23c387bd",
    path: "/js/reg/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23c387bd").then(next)
    },
  },
  {
    name: "v-54eca04e",
    path: "/node/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54eca04e").then(next)
    },
  },
  {
    name: "v-20d1ee7f",
    path: "/node/base/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20d1ee7f").then(next)
    },
  },
  {
    name: "v-237d5cbf",
    path: "/note/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-237d5cbf").then(next)
    },
  },
  {
    path: "/note/index.html",
    redirect: "/note/"
  },
  {
    name: "v-55197a1a",
    path: "/note/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55197a1a").then(next)
    },
  },
  {
    name: "v-711d6edc",
    path: "/note/pit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-711d6edc").then(next)
    },
  },
  {
    name: "v-4b420282",
    path: "/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b420282").then(next)
    },
  },
  {
    path: "/node/index.html",
    redirect: "/node/"
  },
  {
    name: "v-8f606bd8",
    path: "/note/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8f606bd8").then(next)
    },
  },
  {
    name: "v-68ac6a4c",
    path: "/note/react1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68ac6a4c").then(next)
    },
  },
  {
    name: "v-6dfd14c2",
    path: "/plan/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6dfd14c2").then(next)
    },
  },
  {
    path: "/plan/index.html",
    redirect: "/plan/"
  },
  {
    name: "v-31a9387f",
    path: "/plan/plan/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31a9387f").then(next)
    },
  },
  {
    name: "v-81692842",
    path: "/plan/planLong/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81692842").then(next)
    },
  },
  {
    name: "v-3ff7069f",
    path: "/plan/plan/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ff7069f").then(next)
    },
  },
  {
    name: "v-ae03a42e",
    path: "/react/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ae03a42e").then(next)
    },
  },
  {
    path: "/react/index.html",
    redirect: "/react/"
  },
  {
    name: "v-4dd048d2",
    path: "/node/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dd048d2").then(next)
    },
  },
  {
    name: "v-59459c31",
    path: "/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59459c31").then(next)
    },
  },
  {
    path: "/tools/index.html",
    redirect: "/tools/"
  },
  {
    name: "v-6270fde5",
    path: "/react/react/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6270fde5").then(next)
    },
  },
  {
    name: "v-1284205f",
    path: "/node/base/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1284205f").then(next)
    },
  },
  {
    name: "v-c41bedb6",
    path: "/tools/chajian/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c41bedb6").then(next)
    },
  },
  {
    name: "v-e8a03236",
    path: "/tools/git/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e8a03236").then(next)
    },
  },
  {
    name: "v-2c2d5a89",
    path: "/tools/vscode/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c2d5a89").then(next)
    },
  },
  {
    name: "v-168a8c05",
    path: "/react/react/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-168a8c05").then(next)
    },
  },
  {
    name: "v-2e76f30b",
    path: "/tools/vscode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e76f30b").then(next)
    },
  },
  {
    name: "v-e85a5d76",
    path: "/tools/webpack/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e85a5d76").then(next)
    },
  },
  {
    name: "v-1d824225",
    path: "/tools/webpack/4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d824225").then(next)
    },
  },
  {
    name: "v-11b7f6e5",
    path: "/tools/webpack/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11b7f6e5").then(next)
    },
  },
  {
    name: "v-d0c5c6f6",
    path: "/tools/webpack/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0c5c6f6").then(next)
    },
  },
  {
    name: "v-b9313076",
    path: "/tools/webpack/5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b9313076").then(next)
    },
  },
  {
    name: "v-3b25ebdf",
    path: "/ts/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b25ebdf").then(next)
    },
  },
  {
    name: "v-294c8d65",
    path: "/tools/webpack/6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-294c8d65").then(next)
    },
  },
  {
    name: "v-38dc535d",
    path: "/ts/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38dc535d").then(next)
    },
  },
  {
    name: "v-1629e51f",
    path: "/ts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1629e51f").then(next)
    },
  },
  {
    path: "/ts/index.html",
    redirect: "/ts/"
  },
  {
    name: "v-167fa802",
    path: "/ts/base/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-167fa802").then(next)
    },
  },
  {
    name: "v-77c13342",
    path: "/ts/base/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77c13342").then(next)
    },
  },
  {
    name: "v-2e428f45",
    path: "/vue/ES6/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e428f45").then(next)
    },
  },
  {
    name: "v-04bc6cb6",
    path: "/vue/ES6/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04bc6cb6").then(next)
    },
  },
  {
    name: "v-5153eee5",
    path: "/vue/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5153eee5").then(next)
    },
  },
  {
    name: "v-518dd6f6",
    path: "/vue/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-518dd6f6").then(next)
    },
  },
  {
    name: "v-44662b1b",
    path: "/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44662b1b").then(next)
    },
  },
  {
    path: "/vue/index.html",
    redirect: "/vue/"
  },
  {
    name: "v-02e0d263",
    path: "/vue/SourceCode/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02e0d263").then(next)
    },
  },
  {
    name: "v-015ab2b6",
    path: "/vue/SourceCode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-015ab2b6").then(next)
    },
  },
  {
    name: "v-09fd29df",
    path: "/vue/SourceCode/4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09fd29df").then(next)
    },
  },
  {
    name: "v-066efe21",
    path: "/vue/SourceCode/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-066efe21").then(next)
    },
  },
  {
    name: "v-0d8b559d",
    path: "/vue/SourceCode/5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d8b559d").then(next)
    },
  },
  {
    name: "v-464f3bdb",
    path: "/vue/vue3/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-464f3bdb").then(next)
    },
  },
  {
    name: "v-3716c636",
    path: "/vue/vue/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3716c636").then(next)
    },
  },
  {
    name: "v-15156285",
    path: "/vue/vue/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15156285").then(next)
    },
  },
  {
    name: "v-b7076832",
    path: "/vue/vuex/1copy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b7076832").then(next)
    },
  },
  {
    name: "v-9a7bf8c2",
    path: "/vuePress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9a7bf8c2").then(next)
    },
  },
  {
    path: "/vuePress/index.html",
    redirect: "/vuePress/"
  },
  {
    name: "v-71624fcf",
    path: "/vue/vuex/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71624fcf").then(next)
    },
  },
  {
    name: "v-a0cfab78",
    path: "/vuePress/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0cfab78").then(next)
    },
  },
  {
    name: "v-423efb74",
    path: "/vuePress/pit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-423efb74").then(next)
    },
  },
  {
    name: "v-efe8be5e",
    path: "/vue/vuex/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-efe8be5e").then(next)
    },
  },
  {
    name: "v-2e0b4da6",
    path: "/xcx/ES6/ES61.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e0b4da6").then(next)
    },
  },
  {
    name: "v-7134ec6b",
    path: "/xcx/ES6/ES62.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7134ec6b").then(next)
    },
  },
  {
    name: "v-3df75b6d",
    path: "/xcx/Function/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3df75b6d").then(next)
    },
  },
  {
    name: "v-662bd3b1",
    path: "/xcx/JS/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-662bd3b1").then(next)
    },
  },
  {
    name: "v-307d3b6b",
    path: "/xcx/Function/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-307d3b6b").then(next)
    },
  },
  {
    name: "v-2c728e6f",
    path: "/xcx/JS/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c728e6f").then(next)
    },
  },
  {
    name: "v-41271b66",
    path: "/xcx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41271b66").then(next)
    },
  },
  {
    path: "/xcx/index.html",
    redirect: "/xcx/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]