/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\blog\\weixian\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7b5469b6",
    path: "/Photography/back/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b5469b6").then(next)
    },
  },
  {
    name: "v-cc6606c6",
    path: "/Photography/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc6606c6").then(next)
    },
  },
  {
    path: "/Photography/index.html",
    redirect: "/Photography/"
  },
  {
    name: "v-3c81def5",
    path: "/Photography/front/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c81def5").then(next)
    },
  },
  {
    name: "v-1eda290c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1eda290c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-9648a9ba",
    path: "/Photography/back/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9648a9ba").then(next)
    },
  },
  {
    name: "v-117d21d5",
    path: "/Photography/front/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-117d21d5").then(next)
    },
  },
  {
    name: "v-2e0f6896",
    path: "/browser/Console/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e0f6896").then(next)
    },
  },
  {
    name: "v-23fe3515",
    path: "/browser/Console/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23fe3515").then(next)
    },
  },
  {
    name: "v-15f0d896",
    path: "/browser/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15f0d896").then(next)
    },
  },
  {
    name: "v-1ef73ab9",
    path: "/browser/Http/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ef73ab9").then(next)
    },
  },
  {
    name: "v-1cada237",
    path: "/browser/Http/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1cada237").then(next)
    },
  },
  {
    name: "v-65dfb2ef",
    path: "/business/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65dfb2ef").then(next)
    },
  },
  {
    path: "/business/index.html",
    redirect: "/business/"
  },
  {
    name: "v-404bb0a2",
    path: "/business/business/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-404bb0a2").then(next)
    },
  },
  {
    name: "v-7f442e0e",
    path: "/browser/SourceCode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f442e0e").then(next)
    },
  },
  {
    name: "v-96552ae2",
    path: "/business/business/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-96552ae2").then(next)
    },
  },
  {
    name: "v-69ee46c6",
    path: "/css/Css/1%20copy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69ee46c6").then(next)
    },
  },
  {
    path: "/css/Css/1 copy.html",
    redirect: "/css/Css/1%20copy.html"
  },
  {
    path: "/css/Css/1 copy.html",
    redirect: "/css/Css/1%20copy.html"
  },
  {
    name: "v-200c50d5",
    path: "/browser/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-200c50d5").then(next)
    },
  },
  {
    name: "v-32a05235",
    path: "/css/Css/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32a05235").then(next)
    },
  },
  {
    name: "v-e992b4d6",
    path: "/css/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e992b4d6").then(next)
    },
  },
  {
    name: "v-111bcb35",
    path: "/css/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-111bcb35").then(next)
    },
  },
  {
    name: "v-612e7e91",
    path: "/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-612e7e91").then(next)
    },
  },
  {
    path: "/css/index.html",
    redirect: "/css/"
  },
  {
    name: "v-84ba87e2",
    path: "/html/Html/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84ba87e2").then(next)
    },
  },
  {
    name: "v-634117d5",
    path: "/css/Css/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-634117d5").then(next)
    },
  },
  {
    name: "v-0f3dcf72",
    path: "/browser/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f3dcf72").then(next)
    },
  },
  {
    path: "/browser/index.html",
    redirect: "/browser/"
  },
  {
    name: "v-35eb0931",
    path: "/html/Interview/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35eb0931").then(next)
    },
  },
  {
    name: "v-681eeba2",
    path: "/html/Html/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-681eeba2").then(next)
    },
  },
  {
    name: "v-384c8d6f",
    path: "/html/Interview/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-384c8d6f").then(next)
    },
  },
  {
    name: "v-71877762",
    path: "/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71877762").then(next)
    },
  },
  {
    path: "/html/index.html",
    redirect: "/html/"
  },
  {
    name: "v-c14772ae",
    path: "/js/ES6/ES61.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c14772ae").then(next)
    },
  },
  {
    name: "v-623393e2",
    path: "/js/Function/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-623393e2").then(next)
    },
  },
  {
    name: "v-a4abd66e",
    path: "/js/ES6/ES62.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a4abd66e").then(next)
    },
  },
  {
    name: "v-09ec1f6f",
    path: "/js/Function/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09ec1f6f").then(next)
    },
  },
  {
    name: "v-73bdc8cf",
    path: "/js/JS/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73bdc8cf").then(next)
    },
  },
  {
    name: "v-715a4f4f",
    path: "/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-715a4f4f").then(next)
    },
  },
  {
    path: "/js/index.html",
    redirect: "/js/"
  },
  {
    name: "v-187b360f",
    path: "/js/JS/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-187b360f").then(next)
    },
  },
  {
    name: "v-0e7ad108",
    path: "/js/arry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e7ad108").then(next)
    },
  },
  {
    name: "v-6f495b30",
    path: "/js/ast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f495b30").then(next)
    },
  },
  {
    name: "v-4013e80f",
    path: "/js/reg/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4013e80f").then(next)
    },
  },
  {
    name: "v-73c70122",
    path: "/js/JS/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73c70122").then(next)
    },
  },
  {
    name: "v-6f630966",
    path: "/js/reg/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f630966").then(next)
    },
  },
  {
    name: "v-a10381b2",
    path: "/node/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a10381b2").then(next)
    },
  },
  {
    name: "v-a81fd92e",
    path: "/node/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a81fd92e").then(next)
    },
  },
  {
    name: "v-133f812f",
    path: "/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-133f812f").then(next)
    },
  },
  {
    path: "/node/index.html",
    redirect: "/node/"
  },
  {
    name: "v-5c5ddf2f",
    path: "/note/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c5ddf2f").then(next)
    },
  },
  {
    path: "/note/index.html",
    redirect: "/note/"
  },
  {
    name: "v-2156b7ef",
    path: "/node/base/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2156b7ef").then(next)
    },
  },
  {
    name: "v-2fa4860f",
    path: "/node/base/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fa4860f").then(next)
    },
  },
  {
    name: "v-43ccb5aa",
    path: "/note/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43ccb5aa").then(next)
    },
  },
  {
    name: "v-777f01dc",
    path: "/note/react1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-777f01dc").then(next)
    },
  },
  {
    name: "v-b1f9f4b8",
    path: "/note/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1f9f4b8").then(next)
    },
  },
  {
    name: "v-01e1f80f",
    path: "/plan/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01e1f80f").then(next)
    },
  },
  {
    path: "/plan/index.html",
    redirect: "/plan/"
  },
  {
    name: "v-595cf26c",
    path: "/note/pit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-595cf26c").then(next)
    },
  },
  {
    name: "v-407bd00f",
    path: "/plan/plan/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-407bd00f").then(next)
    },
  },
  {
    name: "v-7b9ce36f",
    path: "/plan/planLong/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b9ce36f").then(next)
    },
  },
  {
    name: "v-4ec99e2f",
    path: "/plan/plan/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ec99e2f").then(next)
    },
  },
  {
    name: "v-2bc7d459",
    path: "/react/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2bc7d459").then(next)
    },
  },
  {
    path: "/react/index.html",
    redirect: "/react/"
  },
  {
    name: "v-47e17abe",
    path: "/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47e17abe").then(next)
    },
  },
  {
    path: "/tools/index.html",
    redirect: "/tools/"
  },
  {
    name: "v-7ebc10b5",
    path: "/tools/chajian/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ebc10b5").then(next)
    },
  },
  {
    name: "v-100d4d75",
    path: "/react/react/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-100d4d75").then(next)
    },
  },
  {
    name: "v-cafb0316",
    path: "/tools/git/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cafb0316").then(next)
    },
  },
  {
    name: "v-77b248d6",
    path: "/react/react/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77b248d6").then(next)
    },
  },
  {
    name: "v-3384c2ca",
    path: "/tools/vscode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3384c2ca").then(next)
    },
  },
  {
    name: "v-3817f3ce",
    path: "/tools/vscode/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3817f3ce").then(next)
    },
  },
  {
    name: "v-1afc0316",
    path: "/tools/webpack/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1afc0316").then(next)
    },
  },
  {
    name: "v-6c9cd8d5",
    path: "/tools/webpack/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c9cd8d5").then(next)
    },
  },
  {
    name: "v-78672415",
    path: "/tools/webpack/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78672415").then(next)
    },
  },
  {
    name: "v-03676c96",
    path: "/tools/webpack/4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03676c96").then(next)
    },
  },
  {
    name: "v-f79d2156",
    path: "/tools/webpack/5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f79d2156").then(next)
    },
  },
  {
    name: "v-0a1694f5",
    path: "/tools/webpack/6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a1694f5").then(next)
    },
  },
  {
    name: "v-1a26d122",
    path: "/ts/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a26d122").then(next)
    },
  },
  {
    name: "v-410d1f8f",
    path: "/ts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-410d1f8f").then(next)
    },
  },
  {
    path: "/ts/index.html",
    redirect: "/ts/"
  },
  {
    name: "v-1eba0226",
    path: "/ts/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1eba0226").then(next)
    },
  },
  {
    name: "v-69a5e8e2",
    path: "/ts/base/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69a5e8e2").then(next)
    },
  },
  {
    name: "v-cae77422",
    path: "/ts/base/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cae77422").then(next)
    },
  },
  {
    name: "v-57e2ad96",
    path: "/vue/ES6/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57e2ad96").then(next)
    },
  },
  {
    name: "v-04af6ed5",
    path: "/vue/ES6/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04af6ed5").then(next)
    },
  },
  {
    name: "v-321df675",
    path: "/vue/Interview/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-321df675").then(next)
    },
  },
  {
    name: "v-8ff9c7d6",
    path: "/vue/Interview/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ff9c7d6").then(next)
    },
  },
  {
    name: "v-4364898b",
    path: "/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4364898b").then(next)
    },
  },
  {
    path: "/vue/index.html",
    redirect: "/vue/"
  },
  {
    name: "v-4d71941a",
    path: "/vue/SourceCode/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d71941a").then(next)
    },
  },
  {
    name: "v-3f38e522",
    path: "/vue/SourceCode/4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f38e522").then(next)
    },
  },
  {
    name: "v-548deb96",
    path: "/vue/SourceCode/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-548deb96").then(next)
    },
  },
  {
    name: "v-3502776b",
    path: "/vue/vue3/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3502776b").then(next)
    },
  },
  {
    name: "v-381c8da6",
    path: "/vue/SourceCode/5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-381c8da6").then(next)
    },
  },
  {
    name: "v-46553c9e",
    path: "/vue/SourceCode/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46553c9e").then(next)
    },
  },
  {
    name: "v-8a3d0716",
    path: "/vue/vue/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a3d0716").then(next)
    },
  },
  {
    name: "v-76bedc61",
    path: "/vue/vuex/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76bedc61").then(next)
    },
  },
  {
    name: "v-675ed5d4",
    path: "/vuePress/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-675ed5d4").then(next)
    },
  },
  {
    name: "v-5c42f777",
    path: "/vue/vuex/1copy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c42f777").then(next)
    },
  },
  {
    name: "v-60158b5f",
    path: "/vue/vuex/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60158b5f").then(next)
    },
  },
  {
    name: "v-ac1dd3e2",
    path: "/vuePress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac1dd3e2").then(next)
    },
  },
  {
    path: "/vuePress/index.html",
    redirect: "/vuePress/"
  },
  {
    name: "v-f9291454",
    path: "/vuePress/pit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f9291454").then(next)
    },
  },
  {
    name: "v-e4f56686",
    path: "/xcx/ES6/ES61.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4f56686").then(next)
    },
  },
  {
    name: "v-28fb7bd6",
    path: "/vue/vue/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28fb7bd6").then(next)
    },
  },
  {
    name: "v-15bfdffb",
    path: "/xcx/ES6/ES62.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15bfdffb").then(next)
    },
  },
  {
    name: "v-4231520a",
    path: "/xcx/Function/text2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4231520a").then(next)
    },
  },
  {
    name: "v-273d1206",
    path: "/xcx/Function/text1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-273d1206").then(next)
    },
  },
  {
    name: "v-4e6b5741",
    path: "/xcx/JS/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e6b5741").then(next)
    },
  },
  {
    name: "v-14b211ff",
    path: "/xcx/JS/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14b211ff").then(next)
    },
  },
  {
    name: "v-432a5e86",
    path: "/xcx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-432a5e86").then(next)
    },
  },
  {
    path: "/xcx/index.html",
    redirect: "/xcx/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]