/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "资料库",
  "description": "10点读书",
  "base": "/longweixia/",
  "headTags": [
    [
      "script",
      {
        "src": "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"
      }
    ],
    [
      "script",
      {
        "src": "https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.2/jquery.fancybox.min.js"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "type": "text/css",
        "href": "https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.2/jquery.fancybox.min.css"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "/longweixia/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "一. 更新",
      "frontmatter": {},
      "regularPath": "/tools/git/1.html",
      "relativePath": "tools/git/1.md",
      "key": "v-cafb0316",
      "path": "/tools/git/1.html",
      "headers": [
        {
          "level": 2,
          "title": "一. 更新",
          "slug": "一-更新"
        },
        {
          "level": 3,
          "title": "1. 更新远程分支到本地",
          "slug": "_1-更新远程分支到本地"
        },
        {
          "level": 3,
          "title": "2. 将远程某个分支的代码更新到本地",
          "slug": "_2-将远程某个分支的代码更新到本地"
        },
        {
          "level": 3,
          "title": "3. 将本地一个分支的代码更新到另外一个分支上",
          "slug": "_3-将本地一个分支的代码更新到另外一个分支上"
        },
        {
          "level": 2,
          "title": "二.查看",
          "slug": "二-查看"
        },
        {
          "level": 3,
          "title": "1.查看本地分支",
          "slug": "_1-查看本地分支"
        },
        {
          "level": 3,
          "title": "2.查看所有分支",
          "slug": "_2-查看所有分支"
        },
        {
          "level": 3,
          "title": "3. 给分支添加描述",
          "slug": "_3-给分支添加描述"
        }
      ]
    },
    {
      "title": "思维导图 业务",
      "frontmatter": {},
      "regularPath": "/tools/",
      "relativePath": "tools/README.md",
      "key": "v-47e17abe",
      "path": "/tools/",
      "headers": [
        {
          "level": 3,
          "title": "4",
          "slug": "_4-2"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/home.jpg",
        "actionText": "每日一点 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "知识体系",
            "details": "高效的整理前端知识体系，在大脑中架构出一个自己的图书馆"
          }
        ],
        "footer": "伟尚工作室"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1eda290c",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/tools/vscode/1.html",
      "relativePath": "tools/vscode/1.md",
      "key": "v-3384c2ca",
      "path": "/tools/vscode/1.html",
      "headers": [
        {
          "level": 3,
          "title": "vue怎么 实现调用浏览器打印的功能",
          "slug": "vue怎么-实现调用浏览器打印的功能"
        },
        {
          "level": 2,
          "title": "1. 怎么使用鼠标控制字体大小",
          "slug": "_1-怎么使用鼠标控制字体大小"
        },
        {
          "level": 2,
          "title": "2.怎么查看每一行的代码提交记录",
          "slug": "_2-怎么查看每一行的代码提交记录"
        }
      ]
    },
    {
      "title": "实现一个swagger搜索的插件",
      "frontmatter": {},
      "regularPath": "/tools/chajian/1.html",
      "relativePath": "tools/chajian/1.md",
      "key": "v-7ebc10b5",
      "path": "/tools/chajian/1.html",
      "headers": [
        {
          "level": 2,
          "title": "背景",
          "slug": "背景"
        },
        {
          "level": 2,
          "title": "项目源码",
          "slug": "项目源码"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        },
        {
          "level": 3,
          "title": "目录结构",
          "slug": "目录结构"
        },
        {
          "level": 3,
          "title": "manifest.json",
          "slug": "manifest-json"
        },
        {
          "level": 3,
          "title": "index.js",
          "slug": "index-js"
        },
        {
          "level": 2,
          "title": "发布",
          "slug": "发布"
        }
      ]
    },
    {
      "title": "以下内容为HTML 基础篇（1）",
      "frontmatter": {},
      "regularPath": "/tools/vscode/2.html",
      "relativePath": "tools/vscode/2.md",
      "key": "v-3817f3ce",
      "path": "/tools/vscode/2.html",
      "headers": [
        {
          "level": 2,
          "title": "1. html5新增特性？",
          "slug": "_1-html5新增特性"
        },
        {
          "level": 2,
          "title": "2.行内元素有哪些？块级元素有哪些？ 空(void)元素有那些？",
          "slug": "_2-行内元素有哪些-块级元素有哪些-空-void-元素有那些"
        },
        {
          "level": 2,
          "title": "3.标签上title属性与alt属性的区别是什么",
          "slug": "_3-标签上title属性与alt属性的区别是什么"
        },
        {
          "level": 2,
          "title": "4. 语义化标签",
          "slug": "_4-语义化标签"
        },
        {
          "level": 2,
          "title": "5. iframe有哪些优缺点",
          "slug": "_5-iframe有哪些优缺点"
        },
        {
          "level": 2,
          "title": "6. src与href有什么区别",
          "slug": "_6-src与href有什么区别"
        },
        {
          "level": 2,
          "title": "7. property和attribute的区别是什么",
          "slug": "_7-property和attribute的区别是什么"
        },
        {
          "level": 2,
          "title": "8. HTML5的Web storage的存储方式有两种：sessionStorage和localStorage。",
          "slug": "_8-html5的web-storage的存储方式有两种-sessionstorage和localstorage。"
        },
        {
          "level": 2,
          "title": "9. 常见的浏览器内核有哪些",
          "slug": "_9-常见的浏览器内核有哪些"
        },
        {
          "level": 2,
          "title": "10.  Canvas",
          "slug": "_10-canvas"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/tools/webpack/4.html",
      "relativePath": "tools/webpack/4.md",
      "key": "v-03676c96",
      "path": "/tools/webpack/4.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/tools/webpack/5.html",
      "relativePath": "tools/webpack/5.md",
      "key": "v-f79d2156",
      "path": "/tools/webpack/5.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/tools/webpack/2.html",
      "relativePath": "tools/webpack/2.md",
      "key": "v-1afc0316",
      "path": "/tools/webpack/2.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 概念",
          "slug": "_1-概念"
        },
        {
          "level": 2,
          "title": "2. 打包图片",
          "slug": "_2-打包图片"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/tools/webpack/6.html",
      "relativePath": "tools/webpack/6.md",
      "key": "v-0a1694f5",
      "path": "/tools/webpack/6.html"
    },
    {
      "title": "1. 简单介绍",
      "frontmatter": {},
      "regularPath": "/tools/webpack/3.html",
      "relativePath": "tools/webpack/3.md",
      "key": "v-78672415",
      "path": "/tools/webpack/3.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 简单介绍",
          "slug": "_1-简单介绍"
        },
        {
          "level": 2,
          "title": "2. 基本概念",
          "slug": "_2-基本概念"
        }
      ]
    },
    {
      "title": "侧边栏需要参考以下配置",
      "frontmatter": {},
      "regularPath": "/vuePress/pit.html",
      "relativePath": "vuePress/pit.md",
      "key": "v-f9291454",
      "path": "/vuePress/pit.html",
      "headers": [
        {
          "level": 2,
          "title": "侧边栏需要参考以下配置",
          "slug": "侧边栏需要参考以下配置"
        },
        {
          "level": 2,
          "title": "文章内容参考以下配置",
          "slug": "文章内容参考以下配置"
        },
        {
          "level": 2,
          "title": "怎么放大图片",
          "slug": "怎么放大图片"
        }
      ]
    },
    {
      "title": "2",
      "frontmatter": {},
      "regularPath": "/vuePress/",
      "relativePath": "vuePress/README.md",
      "key": "v-ac1dd3e2",
      "path": "/vuePress/"
    },
    {
      "frontmatter": {},
      "regularPath": "/tools/webpack/1.html",
      "relativePath": "tools/webpack/1.md",
      "key": "v-6c9cd8d5",
      "path": "/tools/webpack/1.html",
      "headers": [
        {
          "level": 2,
          "title": "1 缩小文件的搜索范围",
          "slug": "_1-缩小文件的搜索范围"
        },
        {
          "level": 3,
          "title": "1-1优化Loader配置",
          "slug": "_1-1优化loader配置"
        },
        {
          "level": 3,
          "title": "1-2.优化Loader配置优化resolve.modules配置（resolve项）",
          "slug": "_1-2-优化loader配置优化resolve-modules配置-resolve项"
        },
        {
          "level": 3,
          "title": "1-3.优化resolve.alias配置（resolve项）",
          "slug": "_1-3-优化resolve-alias配置-resolve项"
        },
        {
          "level": 3,
          "title": "1-4. 优化resolve.extensions配置",
          "slug": "_1-4-优化resolve-extensions配置"
        },
        {
          "level": 2,
          "title": "2. 减少冗余代码",
          "slug": "_2-减少冗余代码"
        },
        {
          "level": 2,
          "title": "3. 使用HappyPack多进程解析和处理文件",
          "slug": "_3-使用happypack多进程解析和处理文件"
        },
        {
          "level": 2,
          "title": "4. 使用ParallelUglifyPlugin多进程压缩代码文件",
          "slug": "_4-使用paralleluglifyplugin多进程压缩代码文件"
        },
        {
          "level": 2,
          "title": "5. 使用自动刷新",
          "slug": "_5-使用自动刷新"
        },
        {
          "level": 2,
          "title": "6. 开启模块热替换",
          "slug": "_6-开启模块热替换"
        },
        {
          "level": 2,
          "title": "7. 提取公共代码",
          "slug": "_7-提取公共代码"
        },
        {
          "level": 3,
          "title": "8. 通过webpack-bundle-analyzer分析代码包的大小",
          "slug": "_8-通过webpack-bundle-analyzer分析代码包的大小"
        },
        {
          "level": 2,
          "title": "9. DLL  Plugin",
          "slug": "_9-dll-plugin"
        },
        {
          "level": 2,
          "title": "10. Ignore   Plugin",
          "slug": "_10-ignore-plugin"
        },
        {
          "level": 2,
          "title": "11. JS优化",
          "slug": "_11-js优化"
        }
      ]
    },
    {
      "title": "使用指南",
      "frontmatter": {},
      "regularPath": "/vuePress/guide.html",
      "relativePath": "vuePress/guide.md",
      "key": "v-675ed5d4",
      "path": "/vuePress/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 点击展开或缩起的内容",
          "slug": "_1-点击展开或缩起的内容"
        },
        {
          "level": 2,
          "title": "2. 怎么展示本地图片",
          "slug": "_2-怎么展示本地图片"
        },
        {
          "level": 2,
          "title": "3. 怎么实现点击放大本地图片",
          "slug": "_3-怎么实现点击放大本地图片"
        },
        {
          "level": 2,
          "title": "3. 代码使得代码高亮",
          "slug": "_3-代码使得代码高亮"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "JS",
        "link": "/js/"
      }
    ],
    "sidebar": [
      {
        "path": "/js/",
        "title": "3. JS",
        "children": [
          {
            "title": "基础",
            "children": [
              {
                "path": "/js/JS/1",
                "title": "基础1"
              }
            ]
          }
        ]
      }
    ],
    "sidebarDepth": 4
  }
}